### ISSUE TITLE
Crash when app goes to pause with spinner open

### ISSUE THREAD

**Issue by jatankshirsagar** [miteshpithadiya/SearchableSpinner#114]
When app goes to onPause with searchable spinner open

09-09 10:57:49.908 19463-19463/com.jipl.storedge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jipl.storedge, PID: 19463
    java.lang.RuntimeException: Parcel: unable to marshal value Select
        at android.os.Parcel.writeValue(Parcel.java:1418)
        at android.os.Parcel.writeList(Parcel.java:759)
        at android.os.Parcel.writeValue(Parcel.java:1365)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
        at android.os.Bundle.writeToParcel(Bundle.java:1079)
        at android.os.Parcel.writeBundle(Parcel.java:711)
        at android.app.FragmentState.writeToParcel(Fragment.java:140)
        at android.os.Parcel.writeTypedArray(Parcel.java:1254)
        at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:380)
        at android.os.Parcel.writeParcelable(Parcel.java:1437)
        at android.os.Parcel.writeValue(Parcel.java:1343)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
        at android.os.Bundle.writeToParcel(Bundle.java:1079)
        at android.os.Parcel.writeBundle(Parcel.java:711)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3179)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3438)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by quevon24** [comment]
Use the package from here: https://android-arsenal.com/details/1/3272#!package

Is the latest and that error is gone.

**Comment by dkpapo** [comment]
> Use the package from here: https://android-arsenal.com/details/1/3272#!package
> 
> Is the latest and that error is gone.

work for me but i have a new issue in samsung with android 6 when try to show text color is white

**Comment by mohdqasim** [comment]
work around is try to dismiss dialog when onPause trigger
```
override fun onPause() {
        super.onPause()
        //dismiss the dialog when on pasue trigger
        bindAddSalahTime.masjidSp._searchableListDialog?.dismiss()
    }
```
