### ISSUE TITLE
Exception in ArrayAdapter "NotSerializableException"

### ISSUE THREAD

**Issue by ominfowave** [miteshpithadiya/SearchableSpinner#53]
Fatal Exception: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.toptoche.searchablespinnerlibrary.SearchableSpinner)
       at android.os.Parcel.writeSerializable(Parcel.java:1399)
       at android.os.Parcel.writeValue(Parcel.java:1346)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:649)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1034)
       at android.os.Parcel.writeBundle(Parcel.java:674)
       at android.app.FragmentState.writeToParcel(Fragment.java:144)
       at android.os.Parcel.writeTypedArray(Parcel.java:1202)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
       at android.os.Parcel.writeParcelable(Parcel.java:1368)
       at android.os.Parcel.writeValue(Parcel.java:1273)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:649)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1034)
       at android.os.Parcel.writeBundle(Parcel.java:674)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3031)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3569)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by java.io.NotSerializableException: android.widget.ArrayAdapter
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at android.os.Parcel.writeSerializable(Parcel.java:1394)
       at android.os.Parcel.writeValue(Parcel.java:1346)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:649)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1034)
       at android.os.Parcel.writeBundle(Parcel.java:674)
       at android.app.FragmentState.writeToParcel(Fragment.java:144)
       at android.os.Parcel.writeTypedArray(Parcel.java:1202)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
       at android.os.Parcel.writeParcelable(Parcel.java:1368)
       at android.os.Parcel.writeValue(Parcel.java:1273)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:649)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1034)
       at android.os.Parcel.writeBundle(Parcel.java:674)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3031)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3569)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755

**Comment by carloscte** [comment]
The same as you

**Comment by carloscte** [comment]
@ominfowave, Did you find any solution? Tnks!

**Comment by PonnamKarthik** [comment]
Can you show your java code how you implemented array adapter

**Comment by AnithJo** [comment]
Refer this :+1: : 
https://github.com/AnithJo/android_searchable_spinner/

**Comment by hpatel123** [comment]
Still having the issue.
