### ISSUE TITLE
Crash on home click

### ISSUE THREAD

**Issue by esscheffer** [miteshpithadiya/SearchableSpinner#80]
When I click on the android home button (to "minimize" the app) while the SearchableSpinner selection dialog is showing, it triggers a crash. This is the stacktrace I get:

```
05-30 10:07:40.961 22903-22903/com.scheffer.erik.videogamewishlist E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scheffer.erik.videogamewishlist, PID: 22903
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.toptoche.searchablespinnerlibrary.SearchableSpinner)
        at android.os.Parcel.writeSerializable(Parcel.java:1526)
        at android.os.Parcel.writeValue(Parcel.java:1474)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:723)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
        at android.os.Bundle.writeToParcel(Bundle.java:1133)
        at android.os.Parcel.writeBundle(Parcel.java:763)
        at android.app.FragmentState.writeToParcel(Fragment.java:149)
        at android.os.Parcel.writeTypedArray(Parcel.java:1306)
        at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
        at android.os.Parcel.writeParcelable(Parcel.java:1495)
        at android.os.Parcel.writeValue(Parcel.java:1401)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:723)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
        at android.os.Bundle.writeToParcel(Bundle.java:1133)
        at android.os.Parcel.writeBundle(Parcel.java:763)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3658)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3744)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.io.NotSerializableException: android.widget.ArrayAdapter
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
        at android.os.Parcel.writeSerializable(Parcel.java:1521)
        at android.os.Parcel.writeValue(Parcel.java:1474) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:723) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408) 
        at android.os.Bundle.writeToParcel(Bundle.java:1133) 
        at android.os.Parcel.writeBundle(Parcel.java:763) 
        at android.app.FragmentState.writeToParcel(Fragment.java:149) 
        at android.os.Parcel.writeTypedArray(Parcel.java:1306) 
        at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381) 
        at android.os.Parcel.writeParcelable(Parcel.java:1495) 
        at android.os.Parcel.writeValue(Parcel.java:1401) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:723) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408) 
        at android.os.Bundle.writeToParcel(Bundle.java:1133) 
        at android.os.Parcel.writeBundle(Parcel.java:763) 
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3658) 
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3744) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

The adapter for the spinner is a simple string array adapter created like this:

```
ArrayAdapter(this,
                    android.R.layout.simple_spinner_item,
                    stringList)
                    .apply { setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item) }
```

**Comment by cazador4** [comment]
Same here

**Comment by mohsinhussain** [comment]
Any update on this issue?

**Comment by julio-cezar** [comment]
possible solution [69](https://github.com/miteshpithadiya/SearchableSpinner/issues/69)
