### ISSUE TITLE
Double clicking on the spinner crashes the app

### ISSUE THREAD

**Issue by nipunvv** [miteshpithadiya/SearchableSpinner#95]
When double clicking on the spinner the app crashes with the message
`java.lang.IllegalStateException: Fragment already added: SearchableListDialog`

**Comment by en-Vishal** [comment]
I am facing same issue.......

Fatal Exception: java.lang.IllegalStateException
Fragment already added: SearchableListDialog{426bbb30 #1 TAG}

**Comment by siddarthmodi** [comment]
Facing the issue in com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1

java.lang.IllegalStateException: Fragment already added: SearchableListDialog{5b049b7 #1 TAG}
        at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1695)
        at android.app.BackStackRecord.executeOps(BackStackRecord.java:770)
        at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2391)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2147)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2048)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

Please just use this Solution in the onclicklistners
saving a last click time when clicking will prevent this problem.
i.e.
private long mLastClickTime = 0;
private static final long MIN_CLICK_INTERVAL = 1000; //in millis
...
// inside onCreate or so:
findViewById(R.id.button).setOnClickListener(new OnClickListener() {
    @Override
    public void onClick(View v) {
        // mis-clicking prevention, using threshold of 1000 ms
        if (SystemClock.elapsedRealtime() - mLastClickTime < MIN_CLICK_INTERVAL){
            return;
        }
        mLastClickTime = SystemClock.elapsedRealtime();

        // write onclick code here
    }
}

**Comment by redmedicavital** [comment]
I was having problems with this too... But this helped me:

Solution by **ashwindmk**
[https://github.com/miteshpithadiya/SearchableSpinner/issues/48#issuecomment-308752171](url) 

from the issue: #48

**Comment by sochron** [comment]
just add this OnTouchListener in your spinner.

private long mLastClickTime = 0;
searchablespinner.setOnTouchListener((v, event) -> {
            if (SystemClock.elapsedRealtime() - mLastClickTime < 1000){
                return false;
            }
            mLastClickTime = SystemClock.elapsedRealtime();;
            event.setAction(MotionEvent.ACTION_UP);
            searchablespinner.onTouch(v,event);
            return false;
        });

**Comment by synkrama-aditya-bhandare** [comment]
@sochron Thanks !! 
Updated your solution to work in my project which now avoids the crash.

`AtomicLong mLastClickTime = new AtomicLong();
        searchablespinner.setOnTouchListener((v, event) -> {
            if (SystemClock.elapsedRealtime() - mLastClickTime.get() < 1000){
                return false;
            }
            mLastClickTime.set(SystemClock.elapsedRealtime());;
            event.setAction(MotionEvent.ACTION_UP);
            searchablespinner.onTouch(v,event);
            return false;
        });`

**Comment by Riaz-Mahmud** [comment]
Thanks @aditya-cmile 
Solved my problem.
